[default]
address = "0.0.0.0"
port = 8000

[default.switches]
kindle = true
weather = true
bark = true

[default.kindle]
style = "<0,1,2>"
fonts.main = ""
fonts.weather = ""
fonts.status = ""

[default.weather]
cron = ""
location = ""
key = ""

[default.bark]
url = ""

[default.let_server_run]
token = ""

[default.let_server_run.executors]
echo = { t = "echo", c = "" }
