[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"

[default.kindle]
style = "<0,1,2>"
fonts.main = ""
fonts.weather = ""
fonts.status = ""

[default.weather]
cron = ""
location = ""
key = ""
